#!/bin/bash
set -eu # exit script on errors

nvm use 22.13.1

echo "copy configuration files"
rsync /home/git/www/oneweek/.env .
rsync /home/git/www/oneweek/config.json .
rsync /home/git/www/oneweek/credentials.json .

echo "> npm install in backend"
cd backend
npm ci

# # If build wasn't done on github uncomment this
# echo "> npm run build..."
# npm run build

export MAIN="dist/server.js"

